# Generated by Django 4.2.5 on 2023-09-12 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cart_product_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
